[package]
name = "irgen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.0"
rustfft = "6.1.0"
hound = "3.5.0"
apodize = "1.0.0"
clap = { version = "4.0.32", features = ["derive"] }
